name: Pull and Run BusyBox on Windows Docker Desktop

on:
  workflow_dispatch:

jobs:
  run-busybox:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub using login-action
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DU }}
          password: ${{ secrets.DP }}

      - name: Pull BusyBox image
        run: docker pull busybox

      - name: Run BusyBox container
        run: docker run busybox echo "Hello from BusyBox on Windows!"
