name: Docker Volume Reuse with MongoDB

on:
  workflow_dispatch:

jobs:
  volume-persistence:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker login
      run: |
        echo "${{ secrets.DP }}" | docker login -u "${{ secrets.DU }}" --password-stdin

    - name: Create Docker volume
      run: docker volume create mongo-data

    - name: Run Container A and copy file
      run: |
        docker run -d --name container-a -v mongo-data:/data mongo:latest tail -f /dev/null
        docker cp file.json container-a:/data/file.json
        docker rm -f container-a

    - name: Run Container B and read file
      run: |
        docker run --rm -v mongo-data:/data busybox cat /data/file.json
