
name: Python-test

on: [push]
  
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setting up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
  
      - name: installing dependenciess
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_app.txt
  
      - name: Running the test
        run: |
          pytest --junitxml=pytest-report.xml

      - name: commit and push the file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com" 
          git add pytest-report.xml
          git commit -m "Updated pytest-report.xml"
          git push
