
name: Python-test

on: [push]
  
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setting up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
  
      - name: installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-app.txt
  
      - name: Running the test
        run: |
          pytest --junitxml=pytest-report.xml

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: pytest.xml
        
